name: Deploy 

on:
  push:
    branches:
      - main

jobs:
  list-groups:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Infra Deploy
        uses: azure/arm-deploy@v1
        with: 
          scope: subscription 
          subscriptionId: echo ${{ secrets.AZURE_CREDENTIALS }} | -r ".subscriptionId"
          region: westuk
          template: "./azuredeploy.resourcegroup.json"

      - name: List Resource Groups
        run: |
          az group list -o table

      - name: Deploy 
        run: |
          templateFile="./azuredeploy.json"
          deploymentName="cd_deployment_${{github.sha}}"

          az deployment group create --name $deploymentName --template-file $templateFile --resource-group bootcampBenchmarkResourceGroup


