name: Deploy Resource Group

on:
  push:
    branches:
      - main
    paths:
      - "azuredeploy.resourcegroup.json"
      - "az.resourcegroup.params.staging.json"
      - ".github/workflows/deployrg.yaml"

jobs:
  DeployResourceGroup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group
        run: |
          deploymentName="rg_deployment_${{github.sha}}"

          templateFile="./azuredeploy.resourcegroup.json"

          paramsFile="./az.resourcegroup.params.staging.json"

          az deployment sub create \
          --name $deploymentName \
          --template-file $templateFile \
          --location ukwest \
          --parameters $paramsFile
