name: List Azure AD Groups

on:
  push:
    branches:
      - main

jobs:
  list-groups:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List Azure AD Groups
        run: |
          az ad group list --query "[].{name:displayName}" --output table
