name: Staging Infra Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  DeployResources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group
        run: |
          deploymentName="resource_group_${{github.sha}}"

          templateFile="./az.resourcegroup.template.json"

          paramsFile="./az.resourcegroup.params.staging.json"

          az deployment sub create \
          --name $deploymentName \
          --template-file $templateFile \
          --location ukwest \
          --parameters $paramsFile

      - name: Deploy Resources
        run: |
          deploymentName="resources_deployment_${{github.sha}}"

          templateFile="./az.resources.template.json"

          paramsFile="./az.resources.params.staging.json"

          az deployment group create \
          --name $deploymentName \
          --template-file $templateFile \
          --resource-group bootcampBenchmarkStaging \
          --parameters $paramsFile

      - name: Deploy Secrets to Key Vault
        run: |
          az keyvault secret set \
          --name adzunaAppKey \
          --vault-name bootcampbkeyvaultstag \
          --value ${{secrets.ADZUNA_APP_KEY}} \

    
       
