name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Infra Deploy
        run: |
          deploymentName="rg_deployment_${{github.sha}}"
          az deployment sub create --name $deploymentName --template-file azuredeploy.resourcegroup.json --location ukwest

      - name: List Resource Groups
        run: |
          az group list -o table

      - name: Deploy
        run: |
          templateFile="./azuredeploy.json"
          deploymentName="resources_deployment_${{github.sha}}"

          az deployment group create --name $deploymentName --template-file $templateFile --resource-group bootcampBenchmarkResourceGroup
