name: Production Deployment Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Deploy infrastructure
        run: echo "Deploying version ${{ steps.get_version.outputs.VERSION }} to production"
