name: Deploy Resource Group

on:
  push:
    branches:
      - main
    paths:
      - "azuredeploy.resourcegroup.json"
      - "azuredeploy.resourcegroup.parameters.json"
      - ".github/workflows/deployrg.yaml"

jobs:
  DeployResourceGroup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Infra Deploy
        run: |
          deploymentName="rg_deployment_${{github.sha}}"
          paramsFile="./azuredeploy.resourcegroup.parameters.json"

          templateFile="./azuredeploy.resourcegroup.json"

          az deployment sub create \
          --name $deploymentName \
          --template-file $templateFile \
          --location ukwest \
          --parameters $paramsFile
