name: Infra Terraform Deployment Workflow

on:
  push:
    branches:
      - main

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_2 }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VARS_FILE_NAME: stag.tfvars


jobs:
  DeployResourceGroupAndResources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Initialise Terraform
        run: |
          terraform init

      - name: Create Terraform Plan
        run: |
          terraform plan -var-file=${{ env.TF_VARS_FILE_NAME }} -out=main.tfplan

      - name: Apply Terraform Plan
        run: |
          terraform apply -var-file=${{ env.TF_VARS_FILE_NAME }} -auto-approve main.tfplan

      - name: Add Util Files to Blob Storage
        run: |
          storageAccountName=$(terraform output storageaccountname)
          utilStorageContainerName=$(terraform output utilstoragecontainername)
          skillDictionaryFilePath="./utils/skills_dict.json"

          az storage blob upload \
          --file $skillDictionaryFilePath \
          --container-name $utilStorageContainerName \
          --account-name  $storageAccountNames\
          --overwrite