name: Staging Infra Deployment Workflow

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP_NAME: alexBootcampBenchmarkStaging
  RESOURCE_GROUP_PARAMS_PATH: "./az.resourcegroup.params.staging.json"
  RESOURCES_PARAMS_PATH: "./az.resources.params.staging.json"
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_2 }}
  STORAGE_ACCOUNT_NAME: bootcampbstorageaccstag2
  UTIL_BLOB_CONTAINER_NAME: utilblobcontainer


jobs:
  DeployResources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group
        run: |
          deploymentName="resource_group_${{github.sha}}"

          templateFile="./az.resourcegroup.template.json"

          az deployment sub create \
          --name $deploymentName \
          --template-file $templateFile \
          --location ukwest \
          --parameters ${{ env.RESOURCE_GROUP_PARAMS_PATH }}

      - name: Deploy Resources
        run: |
          deploymentName="resources_deployment_${{github.sha}}"

          templateFile="./az.resources.template.json"

          az deployment group create \
          --name $deploymentName \
          --template-file $templateFile \
          --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
          --parameters ${{ env.RESOURCES_PARAMS_PATH }}

      - name: Add Util Files to Blob Storage
        run: |
        skillDictionaryFilePath="./utils/skills_dict.json"

          az storage blob upload \
          --file $skillDictionaryFilePath \
          --container-name ${{ env.UTIL_BLOB_CONTAINER_NAME }} \
          --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
          --auth-mode login

# check workflow has write access to blob storage